### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LeeLucas-99** [zhang-guodong/ece510project1#2]
Project3 中的 tools中的 addArray()； 的原理是什么能说一下嘛？
为啥switch（sum)？size是指什么？

**Comment by zhang-guodong** [comment]
> Project3 中的 tools中的 addArray()； 的原理是什么能说一下嘛？
> 为啥switch（sum)？size是指什么？

addArray()就是一个二进制加法器，数组a1和a2是要相加的数，数组r是和存放的地方，数组元素用0和1表示他们是二进制。
sum是同一数位相加的和，根据和的不同，分别设置当前位的结果r[i]和是否有进位carry。
size指相加前多少位的数。

**Comment by LeeLucas-99** [comment]
> > Project3 中的 tools中的 addArray()； 的原理是什么能说一下嘛？
> > 为啥switch（sum)？size是指什么？
> 
> addArray()就是一个二进制加法器，数组a1和a2是要相加的数，数组r是和存放的地方，数组元素用0和1表示他们是二进制。
> sum是同一数位相加的和，根据和的不同，分别设置当前位的结果r[i]和是否有进位carry。
> size指相加前多少位的数。

哦哦我明白了， 再问一下CPU中的hasIns(2-5)是指一次最多同时处理5个指令吗？
还有Cpu类中各个属性后面跟的34或者45是指什么，指的不同次序的指令吗？

**Comment by zhang-guodong** [comment]
> > > Project3 中的 tools中的 addArray()； 的原理是什么能说一下嘛？
> > > 为啥switch（sum)？size是指什么？
> > 
> > 
> > addArray()就是一个二进制加法器，数组a1和a2是要相加的数，数组r是和存放的地方，数组元素用0和1表示他们是二进制。
> > sum是同一数位相加的和，根据和的不同，分别设置当前位的结果r[i]和是否有进位carry。
> > size指相加前多少位的数。
> 
> 哦哦我明白了， 再问一下CPU中的hasIns(2-5)是指一次最多同时处理5个指令吗？
> 还有Cpu类中各个属性后面跟的34或者45是指什么，指的不同次序的指令吗？

差不多，代表当前是否有第（2-5）条指令。
比如34，代表阶段3IE和阶段4MA之间的寄存器，在代码里也就是一些中间变量。

**Comment by LeeLucas-99** [comment]
嗷嗷谢谢啦，运算逻辑都懂了，但是我看main中有点问题吧。
输入1-instruction后只要输入大于0的数就会死循环。
同时我看你读完test.txt文件后，放入data变量。后面就没有data变量的使用了，也就是说命令一直没有输入，所以reg和mem中一直是空的。

**Comment by zhang-guodong** [comment]
> 嗷嗷谢谢啦，运算逻辑都懂了，但是我看main中有点问题吧。
> 输入1-instruction后只要输入大于0的数就会死循环。
> 同时我看你读完test.txt文件后，放入data变量。后面就没有data变量的使用了，也就是说命令一直没有输入，所以reg和mem中一直是空的。

我没有遇到死循环。你是不是用了其他的指令序列？还是修改过代码？我需要更多信息才能确定是什么问题。
data只是一个用来从文件往mem1里写数据的中间变量。一开始我就把所有指令放进mem1里了，以后取指是从mem1里取的，与data无关。

**Comment by LeeLucas-99** [comment]
> > 嗷嗷谢谢啦，运算逻辑都懂了，但是我看main中有点问题吧。
> > 输入1-instruction后只要输入大于0的数就会死循环。
> > 同时我看你读完test.txt文件后，放入data变量。后面就没有data变量的使用了，也就是说命令一直没有输入，所以reg和mem中一直是空的。
> 
> 我没有遇到死循环。你是不是用了其他的指令序列？还是修改过代码？我需要更多信息才能确定是什么问题。
> data只是一个用来从文件往mem1里写数据的中间变量。一开始我就把所有指令放进mem1里了，以后取指是从mem1里取的，与data无关。

我也不清楚是什么问题，当我用visual studio编译的时候。在输入instruction模式后，不论输入是什么都是会死循环。
但是用CLion就正常运行，挺奇怪。
顺便问一句，为什么要用到这些方法（arrayToInt()  和  charToMem()）

**Comment by zhang-guodong** [comment]
> > > 嗷嗷谢谢啦，运算逻辑都懂了，但是我看main中有点问题吧。
> > > 输入1-instruction后只要输入大于0的数就会死循环。
> > > 同时我看你读完test.txt文件后，放入data变量。后面就没有data变量的使用了，也就是说命令一直没有输入，所以reg和mem中一直是空的。
> > 
> > 
> > 我没有遇到死循环。你是不是用了其他的指令序列？还是修改过代码？我需要更多信息才能确定是什么问题。
> > data只是一个用来从文件往mem1里写数据的中间变量。一开始我就把所有指令放进mem1里了，以后取指是从mem1里取的，与data无关。
> 
> 我也不清楚是什么问题，当我用visual studio编译的时候。在输入instruction模式后，不论输入是什么都是会死循环。
> 但是用CLion就正常运行，挺奇怪。
> 顺便问一句，为什么要用到这些方法（arrayToInt() 和 charToMem()）

我用clion开发和运行的。
arrayToInt()：数据虽然是用01数组存放的，但我没写加法器啥的，具体运算需要转换成int型计算。
charToMen()：从test.txt中读到的是字符串，需要用它转一下再放到mem1里。
