### ISSUE TITLE
2nd issue

### ISSUE THREAD

**Issue by LeeLucas-99** [zhang-guodong/ece510project1#3]
抱歉再次叨扰，老哥能说一说hazard 如何处理的吗？

**Comment by zhang-guodong** [comment]
> 抱歉再次叨扰，老哥能说一说hazard 如何处理的吗？

用数组regUsing标记寄存器是否被之前的指令调用，如果是，就阻塞当前指令，让它等到所有的寄存器都释放再执行。

**Comment by LeeLucas-99** [comment]
> > 抱歉再次叨扰，老哥能说一说hazard 如何处理的吗？
> 
> 用数组regUsing标记寄存器是否被之前的指令调用，如果是，就阻塞当前指令，让它等到所有的寄存器都释放再执行。

为什么使用cycle模式时候，运行出错，程序没法进行下去，老哥你还记得怎么回事吗？
![image](https://user-images.githubusercontent.com/63830986/115818603-b27eba80-a42f-11eb-80b2-1ff07f7ce036.png)

**Comment by zhang-guodong** [comment]
> > > 抱歉再次叨扰，老哥能说一说hazard 如何处理的吗？
> > 
> > 
> > 用数组regUsing标记寄存器是否被之前的指令调用，如果是，就阻塞当前指令，让它等到所有的寄存器都释放再执行。
> 
> 为什么使用cycle模式时候，运行出错，程序没法进行下去，老哥你还记得怎么回事吗？
> ![image](https://user-images.githubusercontent.com/63830986/115818603-b27eba80-a42f-11eb-80b2-1ff07f7ce036.png)

这不是出错，是你选择只运行一个cycle，只有第一条指令的取指阶段执行，然后程序就结束了。
